name: Cypress E2E Tests

on:
  push:
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '.github/workflows/e2e-tests.yml'
  pull_request:
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install frontend dependencies
        run: npm ci

      - name: Start backend
        run: |
          cd ../backend
          npm ci
          npm run start:dev &
        env:
          NODE_ENV: test

      - name: Start frontend (port 3001)
        run: PORT=3001 npm start &
        env:
          NODE_ENV: test

      - name: Wait for frontend to be ready on port 3001
        run: npx wait-on http://localhost:3001

      - name: Run Cypress tests
        run: npx cypress run
