name: E2E Tests

on:
  push:
    paths:
      - 'frontend/**'
      - 'backend/**'
  pull_request:
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  e2e:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Start frontend server
        run: |
          npm run build
          npm install -g serve
          serve -s build -l 3001 &
        env:
          PORT: 3001

      - name: Wait for frontend to be ready
        run: npx wait-on http://localhost:3001

      - name: Run Cypress E2E tests (with xvfb)
        run: |
          xvfb-run -a npx cypress run
